language: node_js
node_js:
- 12.16.1
cache:
  yarn: true
  directories:
  - node_modules
addons:
  ssh_known_hosts: atid.imd.ufrn.br
script:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
deploy:
  provider: script
  skip_cleanup: true
  script: ssh ${DEPLOY_USER}@${DEPLOY_HOST} "cd ${DEPLOY_DIRECTORY}/atid-react/; bash deploy.sh"
  on:
    branch: master